import React from 'react';
import { FileSpreadsheet, Euro } from 'lucide-react';

export default function ControlNominas({ blockStyle, btnBlackStyle, exportarHorasExcel, labelStyle, inputStyle, fechaInicio, setFechaInicio, fechaFin, setFechaFin, pagoHoraNormal, setPagoHoraNormal, pagoHoraExtra, setPagoHoraExtra, horasTrabajadores }) {
  return (
      <div style={blockStyle}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '25px', flexWrap: 'wrap', gap: '15px' }}><h3 style={{ margin: 0, fontSize: '18px', fontWeight: '300', letterSpacing: '2px', textTransform: 'uppercase' }}>Cálculo de Nóminas y Horas</h3><button onClick={exportarHorasExcel} style={{ ...btnBlackStyle, backgroundColor: '#ffffff', color: '#1a1a1a', border: '1px solid #1a1a1a' }}><FileSpreadsheet size={16} /> Exportar Pagos a Excel</button></div>
          <div style={{ marginBottom: '25px', display: 'flex', gap: '15px', padding: '20px', border: '1px solid #e5e7eb', backgroundColor: '#fafafa', flexWrap: 'wrap' }}><div style={{ flex: 1, minWidth: '150px' }}><label style={labelStyle}>Desde la fecha:</label><input type="date" value={fechaInicio} onChange={(e) => setFechaInicio(e.target.value)} style={inputStyle} /></div><div style={{ flex: 1, minWidth: '150px' }}><label style={labelStyle}>Hasta la fecha:</label><input type="date" value={fechaFin} onChange={(e) => setFechaFin(e.target.value)} style={inputStyle} /></div>
              <div style={{ flex: 1, minWidth: '120px' }}><label style={labelStyle}>Pago Hora Normal (€)</label><div style={{ display: 'flex', alignItems: 'center', backgroundColor: '#fff', border: '1px solid #e5e7eb' }}><input type="number" value={pagoHoraNormal} onChange={(e) => setPagoHoraNormal(Number(e.target.value))} style={{...inputStyle, border: 'none'}} /></div></div>
              <div style={{ flex: 1, minWidth: '120px' }}><label style={{...labelStyle, color: '#2563eb'}}>Pago Hora Extra (€)</label><div style={{ display: 'flex', alignItems: 'center', backgroundColor: '#fff', border: '1px solid #2563eb' }}><input type="number" value={pagoHoraExtra} onChange={(e) => setPagoHoraExtra(Number(e.target.value))} style={{...inputStyle, border: 'none', color: '#2563eb', fontWeight: 'bold'}} /></div></div>
          </div>
          {horasTrabajadores.length === 0 ? <div style={{ textAlign: 'center', padding: '30px', color: '#64748b', fontSize: '12px', letterSpacing: '1px', textTransform: 'uppercase' }}>Sin registros en este periodo</div> : 
           <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(280px, 1fr))', gap: '15px' }}>{horasTrabajadores.map(([nombre, data], index) => { const totalPagar = (data.horas * pagoHoraNormal) + (data.horasExtra * pagoHoraExtra); return ( <div key={index} style={{ padding: '20px', border: '1px solid #1a1a1a', backgroundColor: '#ffffff', display: 'flex', flexDirection: 'column', gap: '10px' }}><div style={{ fontSize: '13px', fontWeight: 'bold', letterSpacing: '1px', textTransform: 'uppercase', borderBottom: '1px solid #e5e7eb', paddingBottom: '10px' }}>{nombre}</div><div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '12px' }}><span style={{ color: '#64748b' }}>Normales:</span> <strong>{data.horas}h <span style={{ color: '#94a3b8', fontWeight: 'normal' }}>(x {pagoHoraNormal}€)</span></strong></div><div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '12px' }}><span style={{ color: '#2563eb', fontWeight: 'bold' }}>Extras:</span> <strong style={{ color: '#2563eb' }}>{data.horasExtra}h <span style={{ fontWeight: 'normal' }}>(x {pagoHoraExtra}€)</span></strong></div><div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginTop: '10px', paddingTop: '10px', borderTop: '1px dashed #e5e7eb' }}><span style={{ fontSize: '10px', fontWeight: 'bold', letterSpacing: '1px' }}>TOTAL A PAGAR:</span><div style={{ fontSize: '22px', fontWeight: '300', display: 'flex', alignItems: 'center', gap: '2px' }}>{totalPagar} <Euro size={18}/></div></div></div> ); })}</div>}
      </div>
  );
}